dist: jammy

language: node_js
node_js:
  - "stable"  # Use the latest stable version of Node.js

cache:
  directories:
    - node_modules  # Cache node_modules to speed up builds

script:
  - npm run build
  - cp CNAME dist/
  - git config --global user.name "Erik Klein"
  - git remote rm origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/erikkl1/erikkl1.github.io.git
  - npm run deploy